Repository CodeCraft-NSU/Database, pull requests merged in 2024-11, with the labels that each got.

#4 [Normal] 학생 계정, 프로젝트, 프로젝트 참여자 관련 쿼리 및 함수 구현
  .gitignore
  PMS_DB_Create.py
  PMS_DB_Drop.py
  PMS_DB_ReCreate.py
  PMS_Student_Management.py
  PMS_Tables_Create.py
  PMS_Tables_Create_byFile.py
  PMS_Tables_Define.sql
  account_DB.py
  mysql_connection.py
  project_DB.py
Labels: Dev

#6 [Normal] 산출물 관련 쿼리 및 함수 구현, DB 및 테이블의 DDL 부분을 함수화, Etc
  PMS_DB_Create.py
  PMS_DB_Drop.py
  PMS_DB_Manage.py
  PMS_DB_ReCreate.py
  PMS_Student_Management.py
  PMS_Tables_Create_byFile.py
  PMS_Tables_Define.sql
  output_DB.py
  project_DB.py
Labels: Dev

#7 [Normal] 진척도(WBS)를 추가, 수정, 삭제, 조회하는 쿼리 및 함수 구현
  wbs_DB.py
Labels: Dev

#8 [Major] DB 접속 함수 수정 및 DML 쿼리문을 수행할 DB가 지정되어 있지 않는 문제 해결
  PMS_DB_Manage.py
  mysql_connection.py
Labels: Dev

#10 [Normal] 예외 발생 시 로그 출력 및 e 객체 반환, 로그아웃 및 토큰 저장 함수 추가
  .gitignore
  account_DB.py
  grade_DB.py
  output_DB.py
  project_DB.py
  task_DB.py
  wbs_DB.py
Labels: Dev

#11 [Major] 프로젝트 참여자(팀원) 추가 함수의 매개 변수에 PM 권한도 입력받도록 수정
  project_DB.py
Labels: Dev

#12 [Servere] ON DELETE CASCADE 옵션을 추가하여 프로젝트 삭제 시 참조 무결성 오류 해결
  PMS_Tables_Define.sql
Labels: Dev

#14 edit_project_user 함수 수정
  account_DB.py
  project_DB.py
Labels: Dev

#15 [Normal] 성적 조회 쿼리에 조인을 적용하여 프로젝트 이름과 학생 이름도 같이 조회되도록 개선
  account_DB.py
  grade_DB.py
  project_DB.py
Labels: Dev

#17 UID 중복 검증 기능 추가
  output_DB.py
  project_DB.py
Labels: Dev

#20 [Severe] 존재하지 않는 PID로 프로젝트가 삭제되는 버그 수정
  .gitignore
  project_DB.py
Labels: bug

#22 로그인 로직 개선
  account_DB.py
Labels: Dev

#23 [Major] 기타 산출물 테이블에 학번 외래키 추가
  PMS_Tables_Define.sql
  output_DB.py
Labels: Dev

#24 [Normal] LLM에 프로젝트 관련 정보를 JSON 형식으로 제공하는 쿼리 및 함수 구현
  project_DB.py
Labels: Dev

#25 [Servere] DELETE 쿼리에서 삭제할 데이터가 없어도 삭제되는 버그 수정
  account_DB.py
  output_DB.py
  project_DB.py
  task_DB.py
  wbs_DB.py
Labels: bug, Dev
