Repository CodeCraft-NSU/Database, pull requests merged in 2025-03, with the labels that each got.

#66 [Major] 전체 학과 정보 조회, 과목 코드로 해당 학과의 교수 목록을 조회하는 쿼리 및 함수 구현
  account_DB.py
Labels: 🖥️ Dev

#68 [Normal] 나머지 다른 학과의 교과목 정보 추가
  PMS_Tables_Define.sql
Labels: 🖥️ Dev

#70 [Major] 프로젝트 정보 조회 함수에서 교번, 교수 이름, 과목 코드, 과목 이름도 같이 조회되도록 수정
  project_DB.py
Labels: 🔥 Bug, 🖥️ Dev

#72 [Major] 교수 계정 로그인 관련 문제 해결
  account_DB.py
Labels: 🔥 Bug

#74 [Major] 프로젝트 개요서, 요구사항 명세서의 작성 일자를 매개 변수로 받도록 수정
  output_DB.py
Labels: 🔥 Bug, 🖥️ Dev

#76 [Major] 프로젝트 번호로 담당 교수 조회 시 교번도 같이 출력되도록 수정
  project_DB.py
Labels: 🖥️ Dev

#78 학번으로 history 테이블을 조회하는 기능 추가
  csv_DB.py
Labels: 🖥️ Dev

#80 [Severe] 프로젝트 개요서 수정 관련 함수에서 작성일 컬럼도 수정할 수 있도록 수정
  output_DB.py
Labels: 🔥 Bug, 🖥️ Dev

#82 [Severe] 요구사항 명세서 수정 함수에서 작성일 컬럼도 수정할 수 있도록 수정, Etc
  account_DB.py
  output_DB.py
Labels: 🔥 Bug, 🖥️ Dev

#84 [Major] 프로젝트 개요서 간단본을 모두 조회하는 함수에서 상세본까지 같이 조회되는 문제 해결
  output_DB.py
Labels: 🔥 Bug, 🖥️ Dev
