Repository CodeCraft-NSU/Database, pull requests merged in 2025-02, with the labels that each got.

#51 [Normal] 프로젝트 Import/Export 기능의 버전 관리를 위한 시퀀스 기능 구현, Etc
  PMS_DB_Manage.py
  PMS_PLSQL_Define.sql
  PMS_Tables_Define.sql
  csv_DB.py
  project_DB.py
Labels: Dev

#52 [Normal] 사용자(학생) 계정의 비밀번호를 찾는 쿼리 및 함수 구현
  account_DB.py
Labels: Dev

#54 [Servere] 프로젝트 정보를 저장하는 insert_csv_history 함수 및 쿼리 구현, 버그 수정 필요
  csv_DB.py
Labels: 🔥Bug, 🖥️Dev

#57 template 문서 업데이트
  .github/ISSUE_TEMPLATE/general.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📋Documentation

#58 [Major] 2/6(목) 대면 미팅 피드백에 따른 DB 수정 작업, 프로젝트 성적 평가 체계 변경, Etc
  PMS_Tables_Define.sql
  account_DB.py
  csv_DB.py
  grade_DB.py
  output_DB.py
  project_DB.py
  subject_DB.py
Labels: 🖥️Dev

#59 [Normal] 테스트 케이스를 한 번에 입력 및 저장하는 방식으로 변경
  PMS_Tables_Define.sql
  output_DB.py
Labels: 🖥️Dev

#61 [Normal] 옵티마이저 힌트 구문과 인덱스를 활용한 SQL 튜닝 및 성능 개선(최적화) 작업
  PMS_Tables_Define.sql
  output_DB.py
  project_DB.py
  subject_DB.py
  task_DB.py
  wbs_DB.py
Labels: 🖥️ Dev

#63 [Major] 프로젝트 생성 시 학과번호는 과목 코드 및 서브쿼리로 자동으로 입력되도록 수정
  project_DB.py
Labels: 🖥️ Dev

#64 [Normal] [CI/CD] Python 자동 컴파일 및 문법 오류 확인 자동화 구축
  .github/workflows/main.yml
Labels: 📋 Documentation, 🛠️ CI/CD
